"""
File to display the truemap
"""
import argparse
import matplotlib.pyplot as plt

def display_map(self, aruco_true_pos, fruits_true_pos):
    '''
    Function provides a preview of the map generated by the path planning algorithm
    but i think this only plots the trueposes
    '''
    # plot result of path planning and show in a figure 
    x_aruco, y_aruco, x_fruits, y_fruits = [],[],[],[]

    for i in range(len(aruco_true_pos)):
        x_aruco.append(aruco_true_pos[i][0])
        y_aruco.append(aruco_true_pos[i][1])
    
    plt.plot(x_aruco, y_aruco, 'ok') 
    for i, (x, y) in enumerate(zip(x_aruco, y_aruco), 1):
        plt.annotate(f'aruco_{i}', (x, y), textcoords="offset points", xytext=(0,-10), ha='center')
    
    # fruit_color = [[128, 0, 0], [155, 255, 70], [255, 85, 0], [255, 180, 0], [0, 128, 0]]
    fruit_colour = ["red", "cyan", "orange", "yellow", "green"]

    for i in range(len(fruits_true_pos)):
        x_fruits.append(fruits_true_pos[i][0])
        y_fruits.append(fruits_true_pos[i][1])
    plt.scatter(x_fruits, y_fruits, c=fruit_colour, s=100)
    for i, (x, y) in enumerate(zip(x_fruits, y_fruits), 1):
        plt.annotate(f'{i+10}', (x, y), textcoords="offset points", xytext=(0,-10), ha='center')
    
    plt.grid(True)
    plt.show() 

if __name__ == "__main__":

    print("hello")
    